### ISSUE TITLE
not sending notifications for multiple receipients if received by role was set in erpnext notifications

### ISSUE THREAD

**Issue by Mar87iam** [ERPGulf/ultramsg_4_ERPNext#2]
good morning
thanks for the application but i noticed that

1-if we created erpnext notification and  receipients were set to be by role

notifications not sent or sent to only one of all the users assigned to this role
2-cant combine system notification with whatsapp notification
3-ultraamsg log report not recording any successful sent whatsapp notification
![Screenshot from 2024-04-18 07-15-19](https://github.com/ERPGulf/ultramsg_4_ERPNext/assets/48872986/ddefc085-280f-4ff1-a72b-20390647d52d)

**Comment by fkalpana** [comment]
Aysha

Please look into this and fix.

Farook Kalpana
00974- 55124924
***@***.***

**Comment by moizsami** [comment]
Yes I can confirm that by role feature is not working.
It is throwing below error:
`Traceback (most recent call last):
  File "apps/ultramsg_4_erpnext/ultramsg_4_erpnext/overrides/notification.py", line 50, in send_whatsapp_with_pdf
    frappe.get_doc({"doctype":"ultramsg_4_ERPNext log","title":"Whatsapp message and pdf successfully sent ","message":msg1,"to_number":doc.custom_mobile_phone,"time":current_time }).insert()
                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SalesInvoice' object has no attribute 'custom_mobile_phone'`

**Comment by fkalpana** [comment]
we have a filed in sales invoice ( custom_mobile_phone ) , to send whatsapp. pls create that, it should work

**Comment by moizsami** [comment]
> we have a filed in sales invoice ( custom_mobile_phone ) , to send whatsapp. pls create that, it should work

I created the field, i didnt get any failed msg error log, but the success log was created with empty mobile number as I had left the field empty.
![image](https://github.com/ERPGulf/ultramsg_4_ERPNext/assets/24491918/52c4ccbf-1f55-4a98-800a-daa9c05c4936)

What I want is based on the role it should get the mobile number. In user form I have filled the 'Mobile No' field with value.

**Comment by moizsami** [comment]
Is there any plan in the near future to fix the send to multiple users based on Role ?

**Comment by fkalpana** [comment]
Send details. lets check

**Comment by moizsami** [comment]
> Send details. lets check

- I have created a new Role. 
- Assigned two users to that role
- Made sure they both have mobile_no field filled in User form
- Once the condition is triggered only one user receives the notification, the second one doesnt.

- Nothing gets written in the ultramsg success log doctype 
- in the error list, new record gets created

```
Traceback (most recent call last):
  File "apps/ultramsg_4_erpnext/ultramsg_4_erpnext/overrides/notification.py", line 90, in send_whatsapp_without_pdf
    frappe.get_doc({"doctype":"ultramsg_4_ERPNext log","title":"Whatsapp message successfully sent ","message":msg1,"to_number":doc.custom_mobile_phone,"time":current_time }).insert()
                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Contact' object has no attribute 'custom_mobile_phone'
```

And if we create the custom field, the error does not appear and the success log is written but with empty 'to_number' field and still the message is sent to only one user.

**Comment by moizsami** [comment]
I think in notification.py, indentation of the return receiver_list statement is incorrect, it should be maybe out of the for loop in order to work correctly.

`			# For sending messages to specified role
            if recipient.receiver_by_role:
                receiver_list += get_info_based_on_role(recipient.receiver_by_role, "mobile_no")
            return receiver_list
  `

**Comment by moizsami** [comment]
Hi just asking is there any update regarding the issue for Multiple users in one role not receiving the message
